import { Profiler, useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { emptyDatabase, demoDatabase, parseImport, exportDatabase, dayKey, dateDay, localDate, supportsDailyRecurrence, tasksForDay, taskTree, createTask, updateTask, completeTask, moveTask, startTimer, pauseTimer, resumeTimer, stopTimer, timerSeconds, duplicateTask, trashTask, restoreTrash, createWorkspace, createProject, type GTDDatabase, type GTDTask, type ActiveTimer } from '../domain';
import { host } from './host';
import { Icon, type IconName } from './icons';

type View = 'today'|'tomorrow'|'week'|'inbox'|'all'|'quadrants'|'calendar'|'project'|'tags'|'filters'|'logs'|'trash'|'focus';
type DeviceSettings = { theme:'light'|'dark'; density:'comfortable'|'compact'; reducedMotion:boolean };
type ImportReview = { database:GTDDatabase; warnings:string[]; name:string };
const views: Array<{id:View; title:string; icon:IconName}> = [{id:'today',title:'今天',icon:'sun'},{id:'tomorrow',title:'明天',icon:'tomorrow'},{id:'week',title:'未来 7 天',icon:'week'},{id:'inbox',title:'收集箱',icon:'inbox'},{id:'all',title:'所有任务',icon:'layers'},{id:'quadrants',title:'四象限',icon:'grid'},{id:'calendar',title:'日历',icon:'calendar'},{id:'tags',title:'标签',icon:'flag'},{id:'filters',title:'过滤器',icon:'menu'},{id:'logs',title:'日志',icon:'clock'},{id:'trash',title:'垃圾箱',icon:'trash'},{id:'focus',title:'专注计时',icon:'clock'}];
const statusNames: Record<string,string> = {inbox:'待整理',open:'待办','in-progress':'进行中',waiting:'等待中',someday:'将来',done:'已完成',cancelled:'已取消'};
const priorityNames: Record<string,string> = {none:'无优先级',low:'低',medium:'中',high:'高'};
const isDone = (task:GTDTask, day?:string) => task.status === 'done' || task.status === 'cancelled' || (!!day && supportsDailyRecurrence(task) && task.completedInstances.includes(day));
const todayAt = (add=0) => { const date=new Date(); date.setDate(date.getDate()+add); return date; };
const dayLabel = (value:string) => { const date=localDate(value); return Number.isNaN(date.getTime()) ? '未安排' : date.toLocaleDateString('zh-CN',{month:'short',day:'numeric'}); };
const timeLabel = (value:string) => new Date(value).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
const toInputDate = (value?:string|null) => value ? dateDay(value) : '';
const toInputDateTime = (value?:string|null) => {if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';return `${dayKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
declare global { interface Window { __plannerQA?: { commits:Array<{phase:string;durationMs:number;at:number}>; marks:Array<{action:string;durationMs:number}> } } }
const recordCommit=(_id:string,phase:string,actualDuration:number)=>{if(!import.meta.env.DEV)return;const qa=window.__plannerQA??={commits:[],marks:[]};qa.commits.push({phase,durationMs:Number(actualDuration.toFixed(2)),at:Math.round(performance.now())});if(qa.commits.length>100)qa.commits.shift();};
const markAction=(action:string)=>{if(!import.meta.env.DEV)return;const start=performance.now();requestAnimationFrame(()=>{const qa=window.__plannerQA??={commits:[],marks:[]};qa.marks.push({action,durationMs:Number((performance.now()-start).toFixed(2))});if(qa.marks.length>100)qa.marks.shift();});};
const errorText = (error:unknown) => {
  const message=error instanceof Error?error.message:String(error);
  const translations:Record<string,string>={
    'A task cannot be moved relative to itself or its descendants':'不能将任务移到自己或自己的子任务前后，也不能放入自己的子任务中。',
    'A task cannot be moved inside itself or its descendants':'不能将任务放入自己或自己的子任务中。',
    'Dragging between workspaces is not supported':'暂不支持在不同工作区之间拖动任务。',
    'Moving tasks across workspaces is not supported':'暂不支持将任务移动到其他工作区。',
    'Stop the current timer before starting another':'请先停止当前计时，再开启另一个计时。',
    'Stop this task’s active timer before moving it to Trash':'请先停止此任务或其子任务的计时，再移到垃圾箱。',
    'Reopen this task before starting a timer':'请先重新打开此任务，再开始计时。',
    'Only today or a past daily occurrence can be completed':'只能完成今天或过去的重复任务，不能提前完成未来的重复实例。',
    'Historical nonrecurring tasks cannot be backdated':'普通任务不能回填完成日期，请在今天完成。',
    'Completing this recurrence is not supported. Its rule has been preserved.':'此重复规则暂不支持完成操作，原规则已保留。',
    'This occurrence was skipped':'此日的重复任务已被跳过。',
    'This occurrence is before the recurrence starts':'所选日期早于此重复任务的开始日期。',
    'Move the parent too, or detach this task before changing its project':'请先将此任务移出父任务，或一起移动父任务，再更换项目。',
    'Task title is required':'请填写任务标题。',
    'Workspace name is required':'请填写工作区名称。',
    'Project name is required':'请填写项目名称。',
    'Restore would overwrite an existing ID. No data was changed.':'恢复操作会覆盖现有记录，已停止恢复，数据未改变。'
  };
  return translations[message]||message;
};
function readSettings(): DeviceSettings { try { const saved=JSON.parse(localStorage.getItem('gtd-device-settings')||'{}'); return {theme:saved.theme==='dark'?'dark':'light',density:saved.density==='compact'?'compact':'comfortable',reducedMotion:!!saved.reducedMotion}; } catch { return {theme:'light',density:'comfortable',reducedMotion:false}; } }

export default function App() {
  const [database,setDatabase]=useState<GTDDatabase|null>(null);
  const dbRef=useRef<GTDDatabase|null>(null);
  const [loading,setLoading]=useState(true);
  const [workspaceID,setWorkspaceID]=useState('');
  const [view,setView]=useState<View>('all');
  const [projectID,setProjectID]=useState('');
  const [selectedID,setSelectedID]=useState<string|null>(null);
  const [query,setQuery]=useState('');
  const [filter,setFilter]=useState<'open'|'all'|'done'>('open');
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [saveState,setSaveState]=useState<'saved'|'pending'|'saving'|'error'>('saved');
  const [sidebarOpen,setSidebarOpen]=useState(false);
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [settings,setSettings]=useState<DeviceSettings>(readSettings);
  const [importReview,setImportReview]=useState<ImportReview|null>(null);
  const [exportReview,setExportReview]=useState(false);
  const [busy,setBusy]=useState(false);
  const [contextMenu,setContextMenu]=useState<{id:string;x:number;y:number}|null>(null);
  const [trashID,setTrashID]=useState<string|null>(null);
  const [entityDialog,setEntityDialog]=useState<'workspace'|'project'|'category'|null>(null);
  const [projectQuery,setProjectQuery]=useState('');
  const [selectedTag,setSelectedTag]=useState('');
  const [collapsedCategories,setCollapsedCategories]=useState<Set<string>>(new Set());
  const [focusMode,setFocusMode]=useState<'stopwatch'|'pomodoro'>('stopwatch');
  const [calendarDate,setCalendarDate]=useState(dayKey(new Date()));
  const [localDay,setLocalDay]=useState(dayKey(new Date()));
  const saveTimeout=useRef<ReturnType<typeof setTimeout>|null>(null);
  const revision=useRef(0);
  const savedRevision=useRef(0);
  const replacementTransaction=useRef<Promise<void>|null>(null);
  const composerRef=useRef<HTMLInputElement>(null);
  const dragID=useRef<string|null>(null);
  const [dragging,setDragging]=useState(false);
  const [collapsed,setCollapsed]=useState<Set<string>>(new Set());
  const currentDay=localDay;
  const targetDay=view==='tomorrow'?dayKey(todayAt(1)):view==='calendar'?calendarDate:currentDay;
  const completionDay=view==='week'?undefined:targetDay;

  const publish=useCallback((db:GTDDatabase)=>{ dbRef.current=db;setDatabase(db); },[]);
  const save=useCallback(async(db:GTDDatabase,version:number)=>{
    setSaveState('saving');
    try { await host.save(db); savedRevision.current=Math.max(savedRevision.current,version); if(revision.current===version)setSaveState('saved'); }
    catch(e) {setSaveState('error');setError(`保存失败：${errorText(e)}。更改仍在当前窗口，请重试保存。`);}
  },[]);
  const mutate=useCallback((recipe:(db:GTDDatabase)=>GTDDatabase)=>{
    if(!dbRef.current||replacementTransaction.current)return;
    try {
      const next=recipe(dbRef.current); publish(next); const version=++revision.current;
      setSaveState('pending'); if(saveTimeout.current)clearTimeout(saveTimeout.current);
      saveTimeout.current=setTimeout(()=>{saveTimeout.current=null;void save(next,version);},300);
    }catch(e){setError(errorText(e));}
  },[publish,save]);
  useEffect(()=>{ let cancelled=false; void host.load().then(result=>{if(cancelled)return; if(result.database){publish(result.database);setWorkspaceID(result.database.workspaces[0]?.id||'');}if(result.recoveryNotice)setNotice(result.recoveryNotice);setLoading(false);}).catch(e=>{if(!cancelled){setLoading(false);setError(`读取失败：${errorText(e)}`);}});return()=>{cancelled=true;};},[publish]);
  useEffect(()=>host.onCloseRequest(async()=>{
    (document.activeElement as HTMLElement|null)?.blur();
    if(replacementTransaction.current)await replacementTransaction.current.catch(()=>{});
    await Promise.resolve();
    if(saveTimeout.current){clearTimeout(saveTimeout.current);saveTimeout.current=null;}
    if(dbRef.current&&revision.current>savedRevision.current){
      const version=revision.current;setSaveState('saving');
      try{await host.save(dbRef.current);savedRevision.current=version;setSaveState('saved');}
      catch(e){setSaveState('error');setError(`关闭前保存失败：${errorText(e)}。请重试保存或导出备份。`);throw e;}
    }
  }),[]);
  useEffect(()=>{if(host.kind!=='browser')return;const flush=()=>{(document.activeElement as HTMLElement|null)?.blur();if(!replacementTransaction.current&&dbRef.current&&revision.current>savedRevision.current){if(saveTimeout.current)clearTimeout(saveTimeout.current);void host.save(dbRef.current);}};window.addEventListener('beforeunload',flush);return()=>window.removeEventListener('beforeunload',flush);},[]);
  useEffect(()=>{const id=setInterval(()=>setLocalDay(dayKey(new Date())),60_000);return()=>clearInterval(id);},[]);
  useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.density=settings.density;document.documentElement.dataset.reducedMotion=String(settings.reducedMotion);try{localStorage.setItem('gtd-device-settings',JSON.stringify(settings));}catch{/* Nonessential device preferences. */}},[settings]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{const element=e.target as HTMLElement;if(e.key==='Escape'){setContextMenu(null);setSelectedID(null);setSidebarOpen(false);}if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('#task-search')?.focus();}if(e.key==='n'&&!e.metaKey&&!e.ctrlKey&&!['INPUT','TEXTAREA','SELECT'].includes(element.tagName)){e.preventDefault();composerRef.current?.focus();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
  useEffect(()=>{if(!contextMenu)return;const close=()=>setContextMenu(null);window.addEventListener('click',close);window.addEventListener('resize',close);return()=>{window.removeEventListener('click',close);window.removeEventListener('resize',close);};},[contextMenu]);
  useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);}},[notice]);

  const workspace=database?.workspaces.find(w=>w.id===workspaceID)||database?.workspaces[0];
  const effectiveWorkspaceID=workspace?.id||'';
  const projects=useMemo(()=>database?.projects.filter(p=>p.workspaceID===effectiveWorkspaceID).sort((a,b)=>a.order-b.order)||[],[database?.projects,effectiveWorkspaceID]);
  const selected=database?.tasks.find(t=>t.id===selectedID);
  const project=projects.find(p=>p.id===projectID);
  const workspaceTasks=useMemo(()=>database?.tasks.filter(t=>t.workspaceID===effectiveWorkspaceID)||[],[database?.tasks,effectiveWorkspaceID]);
  const todayTasks=useMemo(()=>database?tasksForDay(database,effectiveWorkspaceID,currentDay):[],[database,effectiveWorkspaceID,currentDay]);
  const projection=useMemo(()=>{
    if(!database)return [];
    if(view==='today'||view==='tomorrow'||view==='calendar')return tasksForDay(database,effectiveWorkspaceID,targetDay);
    if(view==='week'){const found=new Map<string,GTDTask>();for(let i=1;i<=7;i++)for(const t of tasksForDay(database,effectiveWorkspaceID,dayKey(todayAt(i))))found.set(t.id,t);return [...found.values()];}
    if(view==='inbox')return workspaceTasks.filter(t=>t.status==='inbox');
    if(view==='tags')return workspaceTasks.filter(t=>!selectedTag||t.tags.includes(selectedTag));
    if(view==='project')return workspaceTasks.filter(t=>t.projectID===projectID);
    return workspaceTasks;
  },[database,effectiveWorkspaceID,view,targetDay,workspaceTasks,projectID,selectedTag]);
  const filtered=useMemo(()=>projection.filter(t=>(filter==='all'||(filter==='done'?isDone(t,completionDay):!isDone(t,completionDay)))&&(!query||`${t.title} ${t.note} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[projection,filter,query,completionDay]);
  const ordered=useMemo(()=>{
    if(!database)return [];
    const ids=new Set(filtered.map(t=>t.id));
    const tree=taskTree(database,effectiveWorkspaceID,view==='project'?projectID:undefined);
    const hidden=new Set<string>();
    return tree.filter(({task})=>{if(task.parentID&&(collapsed.has(task.parentID)||hidden.has(task.parentID))){hidden.add(task.id);return false;}return ids.has(task.id);}).map(row=>({...row,depth:Math.min(row.depth,5)}));
  },[database,effectiveWorkspaceID,filtered,view,projectID,collapsed]);
  const childIDs=useMemo(()=>new Set(workspaceTasks.map(t=>t.parentID).filter(Boolean)),[workspaceTasks]);
  const counts=useMemo(()=>({today:todayTasks.filter(t=>!isDone(t,currentDay)).length,inbox:workspaceTasks.filter(t=>t.status==='inbox').length,all:workspaceTasks.filter(t=>!isDone(t)).length}),[todayTasks,workspaceTasks]);

  const navigate=(next:View,project?:string)=>{markAction('navigate');setView(next);setSelectedID(null);if(project)setProjectID(project);setQuery('');setFilter('open');setProjectQuery('');setSidebarOpen(false);};
  const openFocus=(mode:'stopwatch'|'pomodoro')=>{const active=dbRef.current?.activeTimer;setFocusMode(active?.mode||mode);navigate('focus');if(active&&active.mode!==mode)setNotice('请先停止当前计时，再切换计时模式');};
  const startWith=async(demo:boolean)=>{setBusy(true);try{const db=demo?demoDatabase(new Date()):emptyDatabase();await host.save(db);publish(db);setWorkspaceID(db.workspaces[0]?.id||'');setNotice(demo?'示例数据已载入，你可以自由修改':'你的工作区已准备好');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const addTask=(title:string,parentID?:string)=>{
    if(!title.trim())return;
    mutate(db=>{let next=createTask(db,{title:title.trim(),workspaceID:effectiveWorkspaceID,projectID:view==='project'?projectID:undefined,parentID});const task=next.tasks.find(t=>!db.tasks.some(old=>old.id===t.id));if(task){if(view==='today'||view==='tomorrow'||view==='calendar')next=updateTask(next,task.id,{status:'open',plannedStart:targetDay,plannedPrecision:'date'});if(view==='inbox')next=updateTask(next,task.id,{status:'inbox'});setSelectedID(task.id);}return next;});
  };
  const complete=(task:GTDTask)=>mutate(db=>task.completedInstances.includes(targetDay)?updateTask(db,task.id,{completedInstances:task.completedInstances.filter(day=>day!==targetDay)}):isDone(task)?updateTask(db,task.id,{status:'open',completedAt:null}):completeTask(db,task.id,targetDay));
  const duplicate=(id:string)=>mutate(db=>{const next=duplicateTask(db,id);const item=next.tasks.find(t=>!db.tasks.some(old=>old.id===t.id));if(item)setSelectedID(item.id);return next;});
  const importFile=async()=>{
    if(dbRef.current?.activeTimer){setError('请先停止当前计时，再导入文件。暂停中的计时也需要停止。');return;}
    try{const file=await host.importFile();if(file){const parsed=parseImport(file.text);setImportReview({...parsed,name:file.name});}}catch(e){setError(`导入失败：${errorText(e)}`);}
  };
  const commitImport=async()=>{
    if(!importReview)return;if(dbRef.current?.activeTimer){setError('请先停止当前计时，再导入文件。');return;}
    setBusy(true);
    const candidate=importReview.database;
    const transaction=(async()=>{
      try{if(saveTimeout.current){clearTimeout(saveTimeout.current);saveTimeout.current=null;}const version=++revision.current;
        await host.replace(candidate);publish(candidate);savedRevision.current=version;
        setWorkspaceID(candidate.workspaces[0]?.id||'');setSelectedID(null);setView('all');setSaveState('saved');setImportReview(null);setNotice('数据已导入并保存');
      }catch(e){setError(`导入未完成，当前数据未替换：${errorText(e)}`);setSaveState('error');}
    })();
    replacementTransaction.current=transaction;
    try{await transaction;}finally{replacementTransaction.current=null;setBusy(false);}
  };
  const commitExport=async()=>{if(!dbRef.current)return;setBusy(true);try{const exported=await host.exportFile(exportDatabase(dbRef.current));if(exported){setNotice('备份已导出');setExportReview(false);}}catch(e){setError(`导出失败：${errorText(e)}`);}finally{setBusy(false);}};
  const dropTask=(targetID:string,placement:'before'|'after'|'inside')=>{markAction('drop-commit');const id=dragID.current;if(id&&id!==targetID)mutate(db=>moveTask(db,id,targetID,placement));dragID.current=null;setDragging(false);};
  const createEntity=(name:string)=>{
    mutate(db=>{if(entityDialog==='category'){return {...db,projectCategories:[...db.projectCategories,{id:crypto.randomUUID(),workspaceID:effectiveWorkspaceID,name,colorHex:'#2563EB',order:db.projectCategories.filter(c=>c.workspaceID===effectiveWorkspaceID).length}]};}if(entityDialog==='workspace'){const next=createWorkspace(db,name);const item=next.workspaces.find(w=>!db.workspaces.some(old=>old.id===w.id));if(item)setWorkspaceID(item.id);setView('today');setSelectedID(null);return next;}
      const next=createProject(db,effectiveWorkspaceID,name);const item=next.projects.find(p=>!db.projects.some(old=>old.id===p.id));if(item)setProjectID(item.id);setView('project');return next;});setEntityDialog(null);
  };

  if(loading)return <div className="loading-screen"><span className="brand-symbol"><Icon name="check" size={30}/></span><p>正在打开你的工作区…</p></div>;

  return <Profiler id="planner" onRender={recordCommit}><div className={`app ${selected?'inspector-visible':''} ${sidebarOpen?'sidebar-open':''}`}>
    {sidebarOpen&&<button className="sidebar-shade" aria-label="关闭导航" onClick={()=>setSidebarOpen(false)}/>}
    <aside className="source-rail" aria-label="功能入口">
      <div className="rail-top"><span className="rail-app-mark"><Icon name="grid" size={20}/></span></div>
      <nav className="rail-group">{([{id:'inbox',title:'收集箱',icon:'inbox',count:counts.inbox},{id:'all',title:'项目',icon:'folder',count:projects.length},{id:'tags',title:'标签',icon:'flag',count:new Set(workspaceTasks.flatMap(t=>t.tags)).size},{id:'filters',title:'过滤器',icon:'menu',count:0}] as const).map(item=><button key={item.id} title={item.title} aria-label={item.title} aria-current={view===item.id||(item.id==='all'&&view==='project')?'page':undefined} className={`rail-button ${view===item.id||(item.id==='all'&&view==='project')?'active':''}`} onClick={()=>navigate(item.id)}><Icon name={item.icon} size={20}/>{item.count>0&&<span>{item.count>99?'99+':item.count}</span>}</button>)}</nav>
      <nav className="rail-group">{views.filter(v=>['today','tomorrow','week','quadrants','calendar'].includes(v.id)).map(item=><button key={item.id} title={item.title} aria-label={item.title} aria-current={view===item.id?'page':undefined} className={`rail-button ${view===item.id?'active':''}`} onClick={()=>navigate(item.id)}><Icon name={item.icon} size={20}/>{item.id==='today'&&counts.today>0&&<span>{counts.today}</span>}</button>)}</nav>
      <nav className="rail-group">{([{id:'logs',title:'日志',icon:'clock',count:database?.activityLog.length||0},{id:'trash',title:'垃圾箱',icon:'trash',count:database?.trashItems.length||0}] as const).map(item=><button key={item.id} title={item.title} aria-label={item.title} aria-current={view===item.id?'page':undefined} className={`rail-button ${view===item.id?'active':''}`} onClick={()=>navigate(item.id)}><Icon name={item.icon} size={20}/>{item.count>0&&<span>{item.count>99?'99+':item.count}</span>}</button>)}</nav>
      <div className="rail-bottom"><button className="rail-button" title="设置" aria-label="设置" onClick={()=>setSettingsOpen(true)}><Icon name="settings" size={20}/></button><button className="rail-button" title="帮助与迁移状态" aria-label="帮助与迁移状态" onClick={()=>{setSettingsOpen(true);setNotice('这是本地迁移预览；完整迁移范围见设置底部说明');}}><span className="help-symbol">?</span></button></div>
    </aside>
    {(view==='all'||view==='project'||view==='tags')&&<aside className={`project-browser ${sidebarOpen?'mobile-open':''}`} aria-label={view==='tags'?'标签导航':'项目导航'}>
      <div className="project-workspace"><Icon name="grid" size={20}/><select aria-label="当前工作区" value={effectiveWorkspaceID} disabled={!database} onChange={e=>{setWorkspaceID(e.target.value);setProjectID('');setSelectedID(null);setSelectedTag('');navigate(view==='tags'?'tags':'all');}}>{database?.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)||<option>我的工作区</option>}</select><button className="icon-button" title="新建工作区" aria-label="新建工作区" disabled={!database} onClick={()=>setEntityDialog('workspace')}><Icon name="plus" size={15}/></button></div>
      <label className="project-search"><Icon name="search" size={16}/><input value={projectQuery} onChange={e=>setProjectQuery(e.target.value)} placeholder={view==='tags'?'搜索标签':'搜索项目'} aria-label={view==='tags'?'搜索标签':'搜索项目'}/></label>
      <div className="project-browser-content">{view==='tags'?<><button className={`project-item ${!selectedTag?'active':''}`} onClick={()=>setSelectedTag('')}><Icon name="flag" size={16}/><span>全部标签</span></button>{[...new Set(workspaceTasks.flatMap(t=>t.tags))].filter(tag=>tag.toLowerCase().includes(projectQuery.toLowerCase())).sort().map(tag=><button key={tag} className={`project-item ${selectedTag===tag?'active':''}`} onClick={()=>{setSelectedTag(tag);setSelectedID(null);}}><span className="tag-hash">#</span><span>{tag}</span><small>{workspaceTasks.filter(t=>t.tags.includes(tag)).length}</small></button>)}<p className="pane-hint">在任务详情中编辑标签</p></>:<>{[...new Set(['',...(database?.projectCategories.filter(c=>c.workspaceID===effectiveWorkspaceID).map(c=>c.name)||[]),...projects.map(p=>p.category||'')])].map(category=>{const categoryProjects=projects.filter(p=>(p.category||'')===category&&`${p.name} ${category}`.toLowerCase().includes(projectQuery.toLowerCase()));if(projectQuery&&!categoryProjects.length)return null;return <section className="project-category" key={category}><button className="category-toggle" aria-expanded={!collapsedCategories.has(category)} onClick={()=>setCollapsedCategories(old=>{const next=new Set(old);next.has(category)?next.delete(category):next.add(category);return next;})}><span className="project-dot"/><span>{category||'未分组'}</span><small>{categoryProjects.length}</small><Icon name="chevron" size={12} className={collapsedCategories.has(category)?'':'expanded'}/></button>{!collapsedCategories.has(category)&&categoryProjects.map(p=><button key={p.id} className={`project-item ${view==='project'&&projectID===p.id?'active':''}`} onClick={()=>navigate('project',p.id)}><Icon name="folder" size={17} style={{color:p.colorHex||'#2563eb'}}/><span>{p.name}</span><small>{workspaceTasks.filter(t=>t.projectID===p.id&&!isDone(t)).length}</small></button>)}</section>;})}{!projects.length&&<p className="pane-hint">新建一个项目，开始整理任务</p>}</>}</div>
      <div className="project-browser-footer">{view==='tags'?<p>标签源自当前工作区的任务</p>:<><button className="button" disabled={!database} onClick={()=>setEntityDialog('category')}><Icon name="folder" size={15}/>新建分类</button><button className="button" disabled={!database} onClick={()=>setEntityDialog('project')}><Icon name="plus" size={15}/>新建项目</button></>}</div>
    </aside>}
    <div className="workspace-shell">
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="展开导航" onClick={()=>setSidebarOpen(true)}><Icon name="menu"/></button><span className={`save-indicator ${saveState==='error'?'danger-text':''}`}><span className={`status-dot ${saveState==='error'?'danger':''}`}/>{saveState==='saved'?'已保存':saveState==='error'?'保存失败':'保存中…'}</span>{saveState==='error'&&<button className="text-button" onClick={()=>database&&void save(database,revision.current)}>重试</button>}{host.kind==='browser'&&<span className="preview-badge">浏览器预览</span>}</div><div className="original-toolbar"><button className={`button ${view==='focus'&&focusMode==='stopwatch'?'primary':''}`} disabled={!database} onClick={()=>openFocus('stopwatch')}><Icon name="clock" size={16}/>正计时</button><button className={`button ${view==='focus'&&focusMode==='pomodoro'?'primary':''}`} disabled={!database} onClick={()=>openFocus('pomodoro')}><Icon name="clock" size={16}/>番茄钟</button><button className={`button ${view!=='focus'?'toolbar-selected':''}`} disabled={!database} onClick={()=>navigate(projectID?'project':'all',projectID)}><Icon name="layers" size={16}/>任务</button><span title="甘特图尚未迁移，当前预览保留入口位置"><button className="button" disabled><Icon name="calendar" size={16}/>甘特图 <small>待迁移</small></button></span><button className="button toolbar-new" disabled={!database} onClick={()=>{if(['logs','trash','filters','focus'].includes(view))navigate('all');setTimeout(()=>composerRef.current?.focus(),0);}}><Icon name="plus" size={16}/>新建</button></div></header>
      {error&&<div className="alert error" role="alert"><span>{error}</span><button className="icon-button" aria-label="关闭错误" onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}
      {notice&&<div className="notice" role="status"><Icon name="check" size={16}/>{notice}<button className="icon-button" aria-label="关闭提示" onClick={()=>setNotice('')}><Icon name="close" size={14}/></button></div>}
      {!database?<main className="welcome"><div className="welcome-art"><span/><span/><span/><Icon name="check" size={52}/></div><p className="eyebrow">为清晰的每一天</p><h1>给重要的事，留出空间</h1><p>把想法收集成任务，把任务安排进日历。<br/>从一个干净的工作区开始，一步一步向前。</p><div className="welcome-actions"><button className="button primary" disabled={busy} onClick={()=>void startWith(false)}><Icon name="plus"/>创建空白工作区</button><button className="button" disabled={busy} onClick={()=>void startWith(true)}>体验示例数据<Icon name="arrow" size={16}/></button></div><button className="text-button" onClick={()=>void importFile()}><Icon name="upload" size={15}/>已有备份？导入 JSON</button><div className="welcome-footer"><Icon name="layers" size={15}/>本地保存 · 无账户 · 无云同步{host.kind==='browser'&&' · 浏览器预览数据与桌面版分开储存'}</div></main>:<div className="content-layout">
      <main className={`main-content mode-${view}`}>
        <section className="page-heading"><div><h1>{view==='project'?project?.name:view==='all'?'项目任务':view==='tags'?(selectedTag||'全部标签'):view==='focus'?(focusMode==='stopwatch'?'正计时':'番茄钟'):views.find(v=>v.id===view)?.title}</h1><p>{view==='today'||view==='tomorrow'?new Date(`${targetDay}T12:00:00`).toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}):view==='project'?(project?.note||'项目计划'):view==='trash'?'最近删除的内容可在这里恢复':view==='logs'?'查看整理记录与专注记录':view==='all'?'在左侧选择一个项目，或查看全部任务':''}</p></div><div className="heading-actions">{view==='project'&&<span className="count-pill">{projection.length}</span>}<button className="icon-button" title="搜索任务" aria-label="搜索任务" onClick={()=>document.querySelector<HTMLInputElement>('#task-search')?.focus()}><Icon name="search" size={18}/></button></div></section>
        {view==='trash'?<ArchiveTrash database={database} onRestore={id=>mutate(db=>restoreTrash(db,id))}/>:view==='logs'?<ArchiveLogs database={database} workspaceID={effectiveWorkspaceID}/>:view==='filters'?<div className="migration-placeholder"><Icon name="menu" size={30}/><h2>过滤器</h2><p>此入口与原版位置保持一致。自定义过滤器尚未迁移，当前可使用任务搜索、状态筛选与标签视图。</p></div>:view==='focus'?<FocusWorkspace tasks={workspaceTasks} mode={focusMode} activeTimer={database.activeTimer} onStart={(id,mode)=>mutate(db=>startTimer(db,id,mode))}/>:<>

        {(view==='today'||view==='tomorrow')&&<div className="summary-strip"><div><span className="summary-icon blue"><Icon name="layers"/></span><span><strong>{projection.filter(t=>!isDone(t,completionDay)).length}</strong><small>待推进</small></span></div><div><span className="summary-icon orange"><Icon name="clock"/></span><span><strong>{projection.reduce((n,t)=>n+t.executionSlots.filter(s=>dayKey(new Date(s.start))===targetDay).length,0)}</strong><small>计划时段</small></span></div><div><span className="summary-icon green"><Icon name="check"/></span><span><strong>{projection.filter(t=>isDone(t,completionDay)).length}</strong><small>已完成</small></span></div><div className="summary-note"><span>专注一件事</span><strong>就是好的开始</strong></div></div>}
        <div className="list-toolbar"><div className="segmented" aria-label="任务状态筛选">{(['open','all','done'] as const).map(f=><button key={f} className={filter===f?'selected':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f==='open'?'待办':f==='all'?'全部':'已完成'}{f==='open'&&<span>{projection.filter(t=>!isDone(t,completionDay)).length}</span>}</button>)}</div><label className="search-field"><Icon name="search" size={16}/><input id="task-search" placeholder="搜索任务" aria-label="搜索当前视图任务" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label></div>
        <TaskComposer inputRef={composerRef} onAdd={title=>addTask(title)} placeholder={view==='inbox'?'有什么想法？先记在这里…':'添加一个清晰的下一步…'}/>
        {view==='calendar'?<CalendarView database={database} workspaceID={effectiveWorkspaceID} date={calendarDate} query={query} filter={filter} onDate={date=>{markAction('calendar-day');setCalendarDate(date);setSelectedID(null);}} selectedID={selectedID} onSelect={setSelectedID}/>:view==='quadrants'?<QuadrantView tasks={filtered} selectedID={selectedID} onSelect={setSelectedID} onComplete={complete}/>:<section className={`task-list ${dragging?'is-dragging':''}`} aria-label="任务列表"><div className="list-section-heading"><span>{view==='project'?'项目任务':view==='today'?'今天的任务':'任务清单'} <b>{filtered.length}</b></span><span>拖动左侧把手调整顺序 · 中间放入子任务</span></div><VirtualTaskList key={`${effectiveWorkspaceID}:${view}:${projectID}:${selectedTag}:${targetDay}`} rows={ordered} compact={settings.density==='compact'} renderRow={({task,depth})=><TaskRow key={task.id} task={task} completed={isDone(task,completionDay)} depth={depth} projectName={projects.find(p=>p.id===task.projectID)?.name} selected={selectedID===task.id} hasChildren={childIDs.has(task.id)} collapsed={collapsed.has(task.id)} onCollapse={()=>setCollapsed(old=>{const next=new Set(old);next.has(task.id)?next.delete(task.id):next.add(task.id);return next;})} onSelect={()=>{markAction('select-task');setSelectedID(task.id);}} onComplete={()=>complete(task)} onContext={e=>{e.preventDefault();setContextMenu({id:task.id,x:e.clientX,y:e.clientY});}} onMenu={e=>{e.stopPropagation();const rect=e.currentTarget.getBoundingClientRect();setContextMenu({id:task.id,x:rect.right,y:rect.bottom});}} onDragStart={e=>{dragID.current=task.id;setDragging(true);e.dataTransfer.setData('text/plain',task.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{dragID.current=null;setDragging(false);}} onDrop={placement=>dropTask(task.id,placement)}/>} />{!ordered.length&&<EmptyTasks query={query} filter={filter} onAdd={()=>composerRef.current?.focus()}/>}</section>}
        {(view==='today'||view==='tomorrow')&&<DaySchedule tasks={projection} day={targetDay} onSelect={setSelectedID}/>}
        </>}
        <footer className="main-footer"><span>慢慢来，也是在向前</span><span>双击任务查看详情 · 右键更多操作</span></footer>
      </main>
      {!(['logs','trash','filters','focus'].includes(view))&&selected&&<Inspector key={selected.id} task={selected} completed={isDone(selected,completionDay)} database={database} projects={projects} onClose={()=>setSelectedID(null)} onUpdate={patch=>mutate(db=>updateTask(db,selected.id,patch))} onComplete={()=>complete(selected)} onStart={mode=>mutate(db=>startTimer(db,selected.id,mode))} onAddChild={title=>addTask(title,selected.id)} onDuplicate={()=>duplicate(selected.id)} onTrash={()=>setTrashID(selected.id)} onMove={(target,placement)=>mutate(db=>moveTask(db,selected.id,target,placement))}/>} {!selected&&!(['logs','trash','filters','focus'].includes(view))&&<ContextOverview view={view} project={project} workspaceName={workspace?.name||''} tasks={projection} database={database} day={targetDay} onSelect={setSelectedID}/>}
      </div>}
      {database?.activeTimer&&<TimerBar timer={database.activeTimer} onSelect={()=>setSelectedID(database.activeTimer?.taskID||null)} onPause={()=>mutate(db=>pauseTimer(db))} onResume={()=>mutate(db=>resumeTimer(db))} onStop={()=>mutate(db=>stopTimer(db))}/>}
    </div>
    {contextMenu&&<div className="context-menu" role="menu" style={{left:Math.min(contextMenu.x,window.innerWidth-210),top:Math.min(contextMenu.y,window.innerHeight-205)}} onClick={e=>e.stopPropagation()}><button role="menuitem" onClick={()=>{setSelectedID(contextMenu.id);setContextMenu(null);}}><Icon name="edit" size={16}/>编辑任务</button><button role="menuitem" onClick={()=>{const task=database?.tasks.find(t=>t.id===contextMenu.id);if(task)complete(task);setContextMenu(null);}}><Icon name="check" size={16}/>完成 / 重新打开</button><button role="menuitem" onClick={()=>{duplicate(contextMenu.id);setContextMenu(null);}}><Icon name="copy" size={16}/>创建副本</button><hr/><button className="danger-text" role="menuitem" onClick={()=>{setTrashID(contextMenu.id);setContextMenu(null);}}><Icon name="trash" size={16}/>移到废纸篓</button></div>}
    {trashID&&<Modal title="移到废纸篓？" onClose={()=>setTrashID(null)}><p>“{database?.tasks.find(t=>t.id===trashID)?.title}”及其所有子任务将移到废纸篓。之后可以在“偏好设置与数据”的废纸篓中恢复。</p>{database?.activeTimer&&<p className="muted">正在计时的任务不能删除，请先停止计时。</p>}<div className="modal-actions"><button className="button" onClick={()=>setTrashID(null)}>保留任务</button><button className="button danger" onClick={()=>{mutate(db=>trashTask(db,trashID));if(selectedID===trashID)setSelectedID(null);setTrashID(null);}}>移到废纸篓</button></div></Modal>}
    {settingsOpen&&<Modal title="偏好设置与数据" onClose={()=>setSettingsOpen(false)}><p className="muted">外观设置仅保存在此设备，不会写入任务备份。</p><div className="settings-section"><h3>外观</h3><label className="setting-row"><span>配色</span><select value={settings.theme} onChange={e=>setSettings({...settings,theme:e.target.value as DeviceSettings['theme']})}><option value="light">浅色</option><option value="dark">深色</option></select></label><label className="setting-row"><span>列表密度</span><select value={settings.density} onChange={e=>setSettings({...settings,density:e.target.value as DeviceSettings['density']})}><option value="comfortable">舒适</option><option value="compact">紧凑</option></select></label><label className="setting-row"><span>减少动画</span><input type="checkbox" checked={settings.reducedMotion} onChange={e=>setSettings({...settings,reducedMotion:e.target.checked})}/></label></div><div className="settings-section"><h3>你的数据，由你掌握</h3><p className="muted">导入前会校验格式并提供预览，确认后替换当前数据库。桌面版与浏览器预览的数据互相独立。</p><div className="settings-actions"><button className="button" onClick={()=>{setSettingsOpen(false);void importFile();}}><Icon name="upload" size={16}/>导入 JSON</button><button className="button" disabled={!database} onClick={()=>{setSettingsOpen(false);setExportReview(true);}}><Icon name="download" size={16}/>导出备份</button></div></div><div className="settings-section"><h3>废纸篓 · {database?.trashItems.length||0} 项</h3>{database?.trashItems.map(item=><div className="trash-recovery-row" key={item.id}><span>{item.name}<small>{item.tasks.length} 个任务 · {dayLabel(item.deletedAt)}</small></span><button className="text-button" onClick={()=>mutate(db=>restoreTrash(db,item.id))}><Icon name="restore" size={14}/>恢复</button></div>)}{!database?.trashItems.length&&<p className="muted">废纸篓是空的</p>}</div><div className="prototype-note">本地原型 · 支持基础日计划、每日重复与计时；复杂重复规则保留在数据中，暂不完整展开。无账户或云同步。</div></Modal>}
    {importReview&&<Modal title="检查并导入数据" onClose={()=>!busy&&setImportReview(null)}><p>文件：<strong>{importReview.name}</strong></p><div className="import-counts"><div><strong>{importReview.database.workspaces.length}</strong><span>工作区</span></div><div><strong>{importReview.database.projects.length}</strong><span>项目</span></div><div><strong>{importReview.database.tasks.length}</strong><span>任务</span></div></div><div className="alert warning">确认后将替换当前数据，并保留独立的导入前备份。</div>{importReview.warnings.length>0&&<ul className="import-warnings">{importReview.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul>}<div className="modal-actions"><button className="button" disabled={busy} onClick={()=>setImportReview(null)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void commitImport()}>{busy?'正在保存…':'确认替换并导入'}</button></div></Modal>}
    {exportReview&&<Modal title="导出本地备份" onClose={()=>!busy&&setExportReview(false)}><p>将导出所有工作区、任务、计时记录与保留字段为 JSON 文件。请妥善保存，其中可能包含个人信息。</p>{database?.activeTimer&&<div className="alert warning">当前计时仍在运行或暂停。备份会保留状态，但文件导入会拒绝活动计时；建议取消并停止计时后再导出。</div>}<div className="modal-actions"><button className="button" disabled={busy} onClick={()=>setExportReview(false)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void commitExport()}><Icon name="download" size={16}/>{busy?'正在导出…':'选择位置并导出'}</button></div></Modal>}
    {entityDialog&&<NameDialog title={entityDialog==='workspace'?'新建工作区':entityDialog==='category'?'新建分类':'新建项目'} placeholder={entityDialog==='workspace'?'例如：个人生活':entityDialog==='category'?'例如：工作项目':'例如：产品发布'} onClose={()=>setEntityDialog(null)} onSubmit={createEntity}/>}
  </div></Profiler>;
}

function ArchiveTrash({database,onRestore}:{database:GTDDatabase;onRestore:(id:string)=>void}){return <div className="archive-list">{database.trashItems.map(item=><div className="archive-row" key={item.id}><Icon name="trash" size={20}/><div><strong>{item.name}</strong><p>{item.tasks.length} 个任务 · {dayLabel(item.deletedAt)}</p></div><button className="button small" onClick={()=>onRestore(item.id)}><Icon name="restore" size={14}/>恢复</button></div>)}{!database.trashItems.length&&<div className="migration-placeholder"><Icon name="trash" size={30}/><h2>垃圾箱是空的</h2><p>删除的任务及子任务会保存在这里</p></div>}</div>;}
function ArchiveLogs({database,workspaceID}:{database:GTDDatabase;workspaceID:string}){return <div className="archive-list"><h3>专注记录</h3>{database.timeEntries.filter(entry=>entry.workspaceID===workspaceID).slice().reverse().map(entry=><div className="archive-row" key={entry.id}><Icon name="clock" size={18}/><div><strong>{entry.title}</strong><p>{dayLabel(entry.startedAt)} · {timeLabel(entry.startedAt)} – {timeLabel(entry.endedAt)}</p></div><span>{Math.floor((entry.activeSeconds??Math.max(0,(new Date(entry.endedAt).getTime()-new Date(entry.startedAt).getTime())/1000))/60)} 分钟</span></div>)}{!database.timeEntries.length&&<p className="muted">停止一次专注计时后，记录会出现在这里。</p>}<h3>整理记录</h3>{database.activityLog.slice().reverse().map(entry=><div className="archive-row" key={entry.id}><Icon name="layers" size={16}/><div><strong>{entry.action} · {entry.target}</strong><p>{entry.detail}</p></div><span>{dayLabel(entry.timestamp)}</span></div>)}{!database.activityLog.length&&<p className="muted">尚无整理记录。此预览保留导入的历史日志。</p>}</div>;}
function FocusClock({timer,mode}:{timer?:ActiveTimer|null;mode:'stopwatch'|'pomodoro'}){const [now,setNow]=useState(new Date());useEffect(()=>{if(!timer)return;const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id);},[timer]);if(!timer)return <div className="focus-clock">{mode==='pomodoro'?'25:00':'00:00:00'}</div>;const elapsed=timerSeconds(timer,now);const seconds=timer.mode==='pomodoro'?Math.max(0,(timer.targetSeconds||1500)-elapsed):elapsed;return <div className="focus-clock">{String(Math.floor(seconds/3600)).padStart(2,'0')}:{String(Math.floor(seconds%3600/60)).padStart(2,'0')}:{String(Math.floor(seconds%60)).padStart(2,'0')}</div>;}
function FocusWorkspace({tasks,mode,activeTimer,onStart}:{tasks:GTDTask[];mode:'stopwatch'|'pomodoro';activeTimer?:ActiveTimer|null;onStart:(id:string,mode:'stopwatch'|'pomodoro')=>void}){const [taskID,setTaskID]=useState('');return <section className="focus-workspace"><Icon name="clock" size={40}/><FocusClock timer={activeTimer} mode={mode}/><p>{mode==='pomodoro'?'一个番茄时间，只专注一件事':'为当前任务记录专注时间'}</p><label>选择任务<select aria-label="选择专注任务" value={taskID} onChange={e=>setTaskID(e.target.value)}><option value="">请选择一个待办任务</option>{tasks.filter(t=>!isDone(t)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button className="button primary" disabled={!taskID||!!activeTimer} onClick={()=>onStart(taskID,mode)}><Icon name="play" size={15}/>开始{mode==='pomodoro'?'番茄钟':'正计时'}</button>{activeTimer&&<p>计时已开启，请使用窗口底部的暂停、继续与停止控制。</p>}<p className="muted">停止后计入日志。番茄钟到时会提示；自动休息轮转尚未迁移。</p></section>;}
function ContextOverview({view,project,workspaceName,tasks,database,day,onSelect}:{view:View;project?:GTDDatabase['projects'][number];workspaceName:string;tasks:GTDTask[];database:GTDDatabase;day:string;onSelect:(id:string)=>void}){const completed=tasks.filter(t=>isDone(t,day)).length;const overdue=tasks.filter(t=>t.deadline&&toInputDate(t.deadline)<day&&!isDone(t,day)).length;const totalMinutes=database.timeEntries.filter(t=>dayKey(new Date(t.startedAt))===day).reduce((sum,t)=>sum+(t.activeSeconds??Math.max(0,(new Date(t.endedAt).getTime()-new Date(t.startedAt).getTime())/1000))/60,0);return <aside className="context-overview" aria-label={view==='project'?'项目详情':'概览'}><header><Icon name={view==='project'?'folder':'sun'} size={18}/>{view==='project'?'项目详情':view==='today'?'今日概览':'计划概览'}</header>{view==='project'&&project?<div className="project-overview"><h2><Icon name="folder" size={24}/>{project.name}</h2><dl><div><dt>工作区</dt><dd>{workspaceName}</dd></div><div><dt>分类</dt><dd>{project.category||'未分组'}</dd></div><div><dt>任务</dt><dd>{tasks.filter(t=>!isDone(t)).length} 个进行中 · {tasks.length} 个总计</dd></div></dl><h3>项目备注</h3><p>{project.note||'暂无备注'}</p><p className="muted">选择一个任务查看和编辑任务详情</p></div>:<><div className="overview-ring" style={{'--progress':`${tasks.length?completed/tasks.length*100:0}%`} as CSSProperties}><div><strong>{completed}/{tasks.length}</strong><span>已完成</span></div></div><div className="overview-stats"><div><strong>{tasks.length-completed}</strong><span>剩余</span></div><div><strong className="danger-text">{overdue}</strong><span>逾期</span></div><div><strong>{completed}</strong><span>完成</span></div></div><section className="overview-time"><h3><Icon name="clock" size={16}/>时间投入</h3><strong>{Math.floor(totalMinutes)} <small>分钟已记录</small></strong><p>计划时段与实际专注分别统计</p></section><div className="overview-tasks"><h3>优先关注</h3>{tasks.filter(t=>t.priority==='high'&&!isDone(t,day)).slice(0,4).map(task=><button key={task.id} onClick={()=>onSelect(task.id)}><Icon name="flag" size={13}/>{task.title}</button>)}{!tasks.some(t=>t.priority==='high'&&!isDone(t,day))&&<p>当前没有高优先级任务</p>}</div><p className="overview-footer">选择任务以查看详情、安排时间或开启计时</p></>}</aside>;}

function TaskComposer({inputRef,onAdd,placeholder}:{inputRef:React.RefObject<HTMLInputElement|null>;onAdd:(title:string)=>void;placeholder:string}) {const [title,setTitle]=useState('');return <form className="task-composer" onSubmit={e=>{e.preventDefault();if(title.trim()){onAdd(title);setTitle('');}}}><Icon name="plus" size={18}/><input ref={inputRef} value={title} onChange={e=>setTitle(e.target.value)} placeholder={placeholder} aria-label="新任务标题"/><button className={title.trim()?'composer-submit visible':'composer-submit'} disabled={!title.trim()} type="submit">添加 <span>↵</span></button></form>;}

function VirtualTaskList({rows,compact,renderRow}:{rows:Array<{task:GTDTask;depth:number}>;compact:boolean;renderRow:(row:{task:GTDTask;depth:number})=>ReactNode}) {
  const [scrollTop,setScrollTop]=useState(0);
  const ref=useRef<HTMLDivElement>(null);
  const virtual=rows.length>150;
  const rowHeight=compact?50:70;
  const start=virtual?Math.max(0,Math.floor(scrollTop/rowHeight)-5):0;
  const end=virtual?Math.min(rows.length,start+24):rows.length;
  useEffect(()=>{if(ref.current&&ref.current.scrollTop>Math.max(0,rows.length*rowHeight-400)){ref.current.scrollTop=0;setScrollTop(0);}},[rows.length,rowHeight]);
  if(!virtual)return <>{rows.map(renderRow)}</>;
  return <div className="virtual-task-viewport" ref={ref} onScroll={e=>setScrollTop(e.currentTarget.scrollTop)} aria-label={`共 ${rows.length} 个任务，滚动显示更多`}><div style={{height:rows.length*rowHeight,position:'relative'}}><div style={{position:'absolute',top:start*rowHeight,left:0,right:0}}>{rows.slice(start,end).map(row=><div key={row.task.id} style={{height:rowHeight}}>{renderRow(row)}</div>)}</div></div></div>;
}

function TaskRow({task,completed,depth,projectName,selected,hasChildren,collapsed,onCollapse,onSelect,onComplete,onContext,onMenu,onDragStart,onDragEnd,onDrop}:{task:GTDTask;completed:boolean;depth:number;projectName?:string;selected:boolean;hasChildren:boolean;collapsed:boolean;onCollapse:()=>void;onSelect:()=>void;onComplete:()=>void;onContext:(e:React.MouseEvent)=>void;onMenu:(e:React.MouseEvent<HTMLButtonElement>)=>void;onDragStart:(e:React.DragEvent)=>void;onDragEnd:()=>void;onDrop:(placement:'before'|'after'|'inside')=>void}) {
  const ref=useRef<HTMLDivElement>(null);
  const placement=useRef<'before'|'after'|'inside'>('after');
  const clear=()=>{if(ref.current)delete ref.current.dataset.drop;};
  return <div ref={ref} className={`task-row ${selected?'selected':''} ${completed?'completed':''}`} style={{'--depth':depth} as CSSProperties} onContextMenu={onContext} onDragOver={e=>{e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();const y=(e.clientY-rect.top)/rect.height;placement.current=y<.25?'before':y>.75?'after':'inside';e.currentTarget.dataset.drop=placement.current;e.dataTransfer.dropEffect='move';}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))clear();}} onDrop={e=>{e.preventDefault();clear();onDrop(placement.current);}}>
    <span className="drag-handle" draggable onDragStart={onDragStart} onDragEnd={()=>{clear();onDragEnd();}} title="拖动：上 / 下方排序，中间设为子任务"><Icon name="grip" size={16}/></span>
    <div className="task-indent"/>{hasChildren?<button className={`collapse-button ${collapsed?'':'expanded'}`} aria-label={collapsed?'展开子任务':'收起子任务'} aria-expanded={!collapsed} onClick={onCollapse}><Icon name="chevron" size={12}/></button>:<span className="collapse-placeholder"/>}
    <button className={`task-check priority-${task.priority}`} aria-label={completed?`重新打开：${task.title}`:`完成：${task.title}`} aria-pressed={completed} onClick={onComplete}>{completed&&<Icon name="check" size={13}/>}</button>
    <button className="task-main" onClick={onSelect} onDoubleClick={onSelect}><span className="task-title">{task.title}</span><span className="task-meta">{projectName&&<span><span className="tiny-dot"/>{projectName}</span>}{task.status==='in-progress'&&<span className="in-progress">进行中</span>}{task.status==='waiting'&&<span>等待中</span>}{task.executionSlots[0]&&<span><Icon name="clock" size={11}/>{timeLabel(task.executionSlots[0].start)}</span>}{task.tags.slice(0,2).map(tag=><span key={tag}>#{tag}</span>)}{task.recurrence&&task.recurrence!=='none'&&<span title="重复任务">↻ 重复</span>}</span></button>
    {task.deadline&&<span className={`task-due ${toInputDate(task.deadline)<dayKey(new Date())&&!completed?'overdue':''}`}><Icon name="calendar" size={13}/>{dayLabel(task.deadline)}</span>}{task.priority==='high'&&<Icon name="flag" size={15} className="priority-flag"/>}<button className="icon-button row-menu" aria-label={`更多操作：${task.title}`} onClick={onMenu}><Icon name="more" size={17}/></button>
    <span className="drop-label">放入此任务，成为子任务</span>
  </div>;
}
function EmptyTasks({query,filter,onAdd}:{query:string;filter:string;onAdd:()=>void}) {return <div className="empty-tasks"><span><Icon name={query?'search':filter==='done'?'check':'sun'} size={30}/></span><h3>{query?'没有找到匹配的任务':filter==='done'?'还没有已完成的任务':'留一点空间，给重要的事'}</h3><p>{query?'试试其他关键词，或切换任务状态':filter==='done'?'完成一个小行动，就会出现在这里':'添加你的第一个行动，让今天更有方向'}</p>{!query&&filter!=='done'&&<button className="text-button" onClick={onAdd}><Icon name="plus" size={15}/>添加任务</button>}</div>;}

function DaySchedule({tasks,day,onSelect}:{tasks:GTDTask[];day:string;onSelect:(id:string)=>void}){const slots=tasks.flatMap(task=>task.executionSlots.filter(slot=>dayKey(new Date(slot.start))===day).map(slot=>({task,slot}))).sort((a,b)=>a.slot.start.localeCompare(b.slot.start));return <section className="day-schedule"><div className="section-title"><h2><Icon name="clock" size={16}/>计划时段</h2><span>{slots.length?'给计划一个确定的时间':'在任务详情中添加计划时段'}</span></div>{slots.length?<div className="schedule-cards">{slots.map(({task,slot})=><button key={slot.id} className="schedule-card" onClick={()=>onSelect(task.id)}><span>{timeLabel(slot.start)}<span>— {timeLabel(slot.end)}</span></span><strong>{task.title}</strong><small>{Math.round((new Date(slot.end).getTime()-new Date(slot.start).getTime())/60000)} 分钟</small></button>)}</div>:<div className="schedule-empty"><span className="timeline-dot"/><span>还没有安排时段</span><span className="timeline-line"/></div>}</section>;}

function QuadrantView({tasks,selectedID,onSelect,onComplete}:{tasks:GTDTask[];selectedID:string|null;onSelect:(id:string)=>void;onComplete:(task:GTDTask)=>void}) {const today=dayKey(new Date());const buckets=[{title:'重要且紧急',subtitle:'优先行动',className:'urgent',test:(t:GTDTask)=>t.priority==='high'&&!!t.deadline&&toInputDate(t.deadline)<=today},{title:'重要不紧急',subtitle:'留出时间',className:'important',test:(t:GTDTask)=>t.priority==='high'&&(!t.deadline||toInputDate(t.deadline)>today)},{title:'紧急不重要',subtitle:'高效处理',className:'delegate',test:(t:GTDTask)=>t.priority!=='high'&&!!t.deadline&&toInputDate(t.deadline)<=today},{title:'不紧急不重要',subtitle:'适时安排',className:'later',test:(t:GTDTask)=>t.priority!=='high'&&(!t.deadline||toInputDate(t.deadline)>today)}];return <><p className="view-explainer">高优先级 = 重要 · 截止日为今天或已逾期 = 紧急</p><div className="quadrant-grid">{buckets.map((bucket,i)=>{const items=tasks.filter(bucket.test);return <section key={bucket.title} className={`quadrant ${bucket.className}`}><header><div><span className="quadrant-number">0{i+1}</span><h2>{bucket.title}</h2><p>{bucket.subtitle}</p></div><span className="count-pill">{items.length}</span></header><div className="quadrant-tasks">{items.map(task=><div key={task.id} className={`quadrant-task ${selectedID===task.id?'selected':''}`}><button className={`task-check ${isDone(task,today)?'checked':''}`} aria-label={`完成：${task.title}`} onClick={()=>onComplete(task)}>{isDone(task,today)&&<Icon name="check" size={12}/>}</button><button onClick={()=>onSelect(task.id)}>{task.title}{task.deadline&&<small>{dayLabel(task.deadline)} 截止</small>}</button></div>)}{!items.length&&<p className="quadrant-empty">此刻没有任务</p>}</div></section>;})}</div></>;}

function CalendarView({database,workspaceID,date,query,filter,onDate,selectedID,onSelect}:{database:GTDDatabase;workspaceID:string;date:string;query:string;filter:'all'|'open'|'done';onDate:(date:string)=>void;selectedID:string|null;onSelect:(id:string)=>void}) {
  const [month,setMonth]=useState(()=>new Date(`${date.slice(0,7)}-01T12:00:00`));
  const days=useMemo(()=>{const first=new Date(month);first.setDate(1);const offset=(first.getDay()+6)%7;first.setDate(first.getDate()-offset);return Array.from({length:42},(_,index)=>{const d=new Date(first);d.setDate(first.getDate()+index);const key=dayKey(d);return {date:d,key,tasks:tasksForDay(database,workspaceID,key)};});},[database,workspaceID,month]);
  const tasks=tasksForDay(database,workspaceID,date).filter(t=>(filter==='all'||(filter==='done'?isDone(t,date):!isDone(t,date)))&&(!query||`${t.title} ${t.note} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
  return <section className="calendar-view"><header><div><button className="icon-button" aria-label="上个月" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1,12))}><Icon name="chevron" className="rotate-180" size={16}/></button><h2>{month.toLocaleDateString('zh-CN',{year:'numeric',month:'long'})}</h2><button className="icon-button" aria-label="下个月" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1,12))}><Icon name="chevron" size={16}/></button></div><button className="button small" onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1,12));onDate(dayKey(now));}}>回到今天</button></header><div className="calendar-weekdays">{['一','二','三','四','五','六','日'].map(day=><span key={day}>周{day}</span>)}</div><div className="calendar-grid">{days.map(item=><button key={item.key} aria-label={`${item.key}，${item.tasks.length} 个任务`} aria-pressed={item.key===date} className={`calendar-day ${item.date.getMonth()!==month.getMonth()?'outside':''} ${item.key===date?'selected':''} ${item.key===dayKey(new Date())?'today':''}`} onClick={()=>onDate(item.key)}><span>{item.date.getDate()}</span><div>{item.tasks.slice(0,2).map(task=><small key={task.id}>{task.title}</small>)}{item.tasks.length>2&&<em>+{item.tasks.length-2} 项</em>}</div></button>)}</div><div className="calendar-agenda"><div className="section-title"><h2>{dayLabel(date)} 的任务</h2><span>{tasks.length} 项</span></div>{tasks.map(task=><button className={`agenda-task ${selectedID===task.id?'selected':''}`} key={task.id} onClick={()=>onSelect(task.id)}><span className="agenda-dot"/><span>{task.title}</span><small>{task.executionSlots.find(s=>dayKey(new Date(s.start))===date)?timeLabel(task.executionSlots.find(s=>dayKey(new Date(s.start))===date)!.start):'全天'}</small></button>)}{!tasks.length&&<p className="calendar-no-tasks">这一天还没有安排，上方添加的新任务将安排到此日。</p>}</div></section>;
}

function TimerBar({timer,onSelect,onPause,onResume,onStop}:{timer:ActiveTimer;onSelect:()=>void;onPause:()=>void;onResume:()=>void;onStop:()=>void}) {const [now,setNow]=useState(()=>new Date());useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id);},[]);const elapsed=timerSeconds(timer,now);const remaining=timer.mode==='pomodoro'&&timer.targetSeconds?Math.max(0,timer.targetSeconds-elapsed):elapsed;const display=`${String(Math.floor(remaining/3600)).padStart(2,'0')}:${String(Math.floor(remaining%3600/60)).padStart(2,'0')}:${String(Math.floor(remaining%60)).padStart(2,'0')}`;return <div className={`timer-bar ${timer.pausedAt?'paused':''}`}><div className="timer-leading"><span className="timer-pulse"/><span>{timer.pausedAt?'已暂停':timer.mode==='pomodoro'?'番茄专注':'正在专注'}</span><button onClick={onSelect}>{timer.title}</button></div><span className="timer-display" aria-label={`计时 ${display}`}>{display}</span>{timer.mode==='pomodoro'&&remaining===0&&<span className="timer-finished">时间到，停止以保存记录</span>}<button className="timer-control" onClick={timer.pausedAt?onResume:onPause} aria-label={timer.pausedAt?'继续计时':'暂停计时'}><Icon name={timer.pausedAt?'play':'pause'} size={16}/>{timer.pausedAt?'继续':'暂停'}</button><button className="timer-control stop" onClick={onStop}><Icon name="stop" size={13}/>停止并记录</button></div>;}

function Inspector({task,completed,database,projects,onClose,onUpdate,onComplete,onStart,onAddChild,onDuplicate,onTrash,onMove}:{task:GTDTask;completed:boolean;database:GTDDatabase;projects:GTDDatabase['projects'];onClose:()=>void;onUpdate:(patch:Partial<GTDTask>)=>void;onComplete:()=>void;onStart:(mode:'stopwatch'|'pomodoro')=>void;onAddChild:(title:string)=>void;onDuplicate:()=>void;onTrash:()=>void;onMove:(target:string,placement:'before'|'after'|'inside')=>void}) {
  const [title,setTitle]=useState(task.title);const [note,setNote]=useState(task.note||'');const [tagText,setTagText]=useState(task.tags.join(', '));const [child,setChild]=useState('');const [slotStart,setSlotStart]=useState(`${dayKey(new Date())}T09:00`);const [slotEnd,setSlotEnd]=useState(`${dayKey(new Date())}T10:00`);const [slotError,setSlotError]=useState('');const [moveTarget,setMoveTarget]=useState('');const [placement,setPlacement]=useState<'before'|'after'|'inside'>('inside');
  useEffect(()=>setTitle(task.title),[task.title]);useEffect(()=>setNote(task.note||''),[task.note]);useEffect(()=>setTagText(task.tags.join(', ')),[task.tags]);
  const children=database.tasks.filter(t=>t.parentID===task.id);
  const logs=database.timeEntries.filter(entry=>entry.taskID===task.id);
  const addSlot=()=>{const start=new Date(slotStart),end=new Date(slotEnd);if(!slotStart||!slotEnd||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start){setSlotError('结束时间必须晚于开始时间');return;}setSlotError('');onUpdate({executionSlots:[...task.executionSlots,{id:crypto.randomUUID(),start:start.toISOString(),end:end.toISOString()}]});};
  return <aside className="inspector" aria-label="任务详情"><header><span><Icon name="edit" size={15}/>任务详情</span><button className="icon-button" aria-label="关闭任务详情" onClick={onClose}><Icon name="close" size={18}/></button></header><div className="inspector-body"><div className="inspector-title"><button className={`task-check ${completed?'checked':''}`} aria-label={completed?'重新打开任务':'完成任务'} onClick={onComplete}>{completed&&<Icon name="check" size={15}/>}</button><textarea aria-label="任务标题" value={title} rows={2} onChange={e=>setTitle(e.target.value)} onBlur={()=>{if(title.trim()&&title!==task.title)onUpdate({title:title.trim()});else setTitle(task.title);}}/></div><div className="detail-actions"><button className="button primary" disabled={!!database.activeTimer||completed} onClick={()=>onStart('stopwatch')}><Icon name="play" size={15}/>开始专注</button><button className="button" disabled={!!database.activeTimer||completed} onClick={()=>onStart('pomodoro')}><Icon name="clock" size={15}/>25 分钟</button></div>{database.activeTimer&&<p className="inline-note">已有计时，请在底部控制条暂停或停止</p>}
    <div className="detail-fields"><label><span><Icon name="layers" size={15}/>状态</span><select value={task.status} onChange={e=>e.target.value==='done'?onComplete():onUpdate({status:e.target.value as GTDTask['status'],completedAt:null})}>{Object.entries(statusNames).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label><span><Icon name="flag" size={15}/>优先级</span><select value={task.priority} onChange={e=>onUpdate({priority:e.target.value as GTDTask['priority']})}>{Object.entries(priorityNames).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label><span><Icon name="folder" size={15}/>项目</span><select value={task.projectID||''} onChange={e=>onUpdate({projectID:e.target.value||null,sectionID:null,parentID:null})}><option value="">无项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span><Icon name="calendar" size={15}/>{task.plannedPrecision==='minute'?'计划日（改为全天）':'计划日期'}</span><input type="date" value={toInputDate(task.plannedStart)} onChange={e=>onUpdate({plannedStart:e.target.value||null,plannedPrecision:e.target.value?'date':'none',...(!e.target.value?{plannedEnd:null}:{})})}/></label><label><span><Icon name="calendar" size={15}/>计划结束</span><input type="date" min={toInputDate(task.plannedStart)} value={toInputDate(task.plannedEnd)} onChange={e=>onUpdate({plannedEnd:e.target.value||null})}/></label><label><span><Icon name="flag" size={15}/>截止日期</span><input type="date" value={toInputDate(task.deadline)} onChange={e=>onUpdate({deadline:e.target.value||null,deadlinePrecision:e.target.value?'date':'none'})}/></label><label><span><span className="field-symbol">↻</span>重复</span><select value={!task.recurrence||task.recurrence==='none'?'none':supportsDailyRecurrence(task)?'daily':'custom'} onChange={e=>{if(e.target.value!=='custom')onUpdate({recurrence:e.target.value==='daily'?'RRULE:FREQ=DAILY':''});}}><option value="none">不重复</option><option value="daily">每天</option>{task.recurrence&&!supportsDailyRecurrence(task)&&<option value="custom">已导入的重复规则</option>}</select></label><label><span><span className="field-symbol">#</span>标签</span><input value={tagText} placeholder="用逗号分隔" onChange={e=>setTagText(e.target.value)} onBlur={()=>onUpdate({tags:tagText.split(/[,，]/).map(t=>t.trim()).filter(Boolean)})}/></label></div>
    <section className="inspector-section"><h3><Icon name="edit" size={15}/>备注</h3><textarea className="note-input" placeholder="添加背景、想法或下一步…" value={note} onChange={e=>setNote(e.target.value)} onBlur={()=>{if(note!==task.note)onUpdate({note});}} rows={4}/></section>
    <section className="inspector-section"><h3><Icon name="clock" size={15}/>计划时段 <span>{task.executionSlots.length}</span></h3>{task.executionSlots.map(slot=><div className="slot-row" key={slot.id}><div><strong>{dayLabel(slot.start)}</strong><span>{timeLabel(slot.start)} – {timeLabel(slot.end)}</span></div><button className="icon-button" aria-label="删除此计划时段" onClick={()=>onUpdate({executionSlots:task.executionSlots.filter(s=>s.id!==slot.id)})}><Icon name="close" size={14}/></button></div>)}<div className="slot-form"><label>开始<input type="datetime-local" value={slotStart} onChange={e=>setSlotStart(e.target.value)}/></label><label>结束<input type="datetime-local" value={slotEnd} onChange={e=>setSlotEnd(e.target.value)}/></label><button className="text-button" onClick={addSlot}><Icon name="plus" size={14}/>添加时段</button>{slotError&&<p className="danger-text" role="alert">{slotError}</p>}</div></section>
    <section className="inspector-section"><h3><Icon name="layers" size={15}/>子任务 <span>{children.length}</span></h3>{children.map(child=><div className="child-row" key={child.id}><Icon name={isDone(child)?'check':'chevron'} size={13}/>{child.title}</div>)}<form className="child-form" onSubmit={e=>{e.preventDefault();if(child.trim()){onAddChild(child.trim());setChild('');}}}><input value={child} onChange={e=>setChild(e.target.value)} placeholder="添加子任务" aria-label="子任务标题"/><button className="icon-button" type="submit" disabled={!child.trim()} aria-label="添加子任务"><Icon name="plus" size={16}/></button></form></section>
    <details className="inspector-section move-section"><summary>移动与层级 <Icon name="chevron" size={13}/></summary><p className="muted">也可使用此处完成拖动操作。不能将任务移入自己的子任务。</p><select aria-label="移动目标任务" value={moveTarget} onChange={e=>setMoveTarget(e.target.value)}><option value="">选择目标任务</option>{database.tasks.filter(t=>t.workspaceID===task.workspaceID&&t.id!==task.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select aria-label="放置位置" value={placement} onChange={e=>setPlacement(e.target.value as typeof placement)}><option value="inside">成为其子任务</option><option value="before">放在前面（同级）</option><option value="after">放在后面（同级）</option></select><button className="button small" disabled={!moveTarget} onClick={()=>onMove(moveTarget,placement)}>应用移动</button></details>
    <div className="inspector-meta"><span>已记录 {logs.length} 次专注</span><span>创建于 {dayLabel(task.createdAt)}</span></div>
    </div><footer><button className="text-button" onClick={onDuplicate}><Icon name="copy" size={14}/>复制任务</button><button className="icon-button danger-text" aria-label="将任务移到废纸篓" onClick={onTrash}><Icon name="trash" size={16}/></button></footer></aside>;
}

function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('button,input,select')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();closeRef.current();}if(e.key==='Tab'){const elements=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')||[]);const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);previous?.focus();};},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" aria-label="关闭对话框" onClick={onClose}><Icon name="close" size={18}/></button></header><div className="modal-body">{children}</div></div></div>;}
function NameDialog({title,placeholder,onClose,onSubmit}:{title:string;placeholder:string;onClose:()=>void;onSubmit:(name:string)=>void}){const [name,setName]=useState('');return <Modal title={title} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(name.trim())onSubmit(name.trim());}}><label className="name-label">名称<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={placeholder} maxLength={80}/></label><div className="modal-actions"><button className="button" type="button" onClick={onClose}>取消</button><button className="button primary" type="submit" disabled={!name.trim()}>创建</button></div></form></Modal>;}
