import { useMemo, useState, type ReactNode } from 'react';
import { makeScheduleSelection, idKey, sameID, supportsDailyRecurrence, setTaskCompletionForDay, type GTDDatabase, type GTDTask, type TimeEntry } from '../../domain';
import { Icon } from '../icons';
import { ActualEditor, PlanDetails, PlanEditor } from './TodayEditors';
import { TodayModal } from './TodayModal';
import { TodaySchedule } from './TodaySchedule';
import { clockLabel, completedOn, drawerLabels, drawerTasks, durationLabel, rangeLabel, type DrawerFilter, type Mutation, type PlanBlock, type Selection, type TodaySnapshot } from './model';
import './today.css';

type Editor = { type: 'plan'; selection?: Selection; taskID?: string | null } | { type: 'actual'; selection?: Selection; entry?: TimeEntry } | { type: 'plan-detail'; block: PlanBlock };
export function TodayPane({ database, workspaceID, day, snapshot, selectedID, onSelect, query, onQuery, mode, onMode, mutate, composer }: { database: GTDDatabase; workspaceID: string; day: string; snapshot: TodaySnapshot; selectedID: string | null; onSelect: (id: string | null) => void; query: string; onQuery: (query: string) => void; mode: 'list' | 'schedule'; onMode: (mode: 'list' | 'schedule') => void; mutate: Mutation; composer: ReactNode }) {
  const [drawer, setDrawer] = useState<DrawerFilter | null>(null);
  const [editor, setEditor] = useState<Editor | null>(null);
  const [status, setStatus] = useState<'all' | 'open' | 'done'>('all');
  const projectNames = useMemo(() => new Map(database.projects.map(project => [idKey(project.id), project.name])), [database.projects]);
  const filtered = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase();
    if (!needle) return snapshot;
    const ids = new Set(snapshot.tasks.filter(task => `${task.title} ${task.note} ${task.tags.join(' ')} ${task.contexts.join(' ')} ${projectNames.get(idKey(task.projectID || '')) || ''}`.toLocaleLowerCase().includes(needle)).map(task => idKey(task.id)));
    const taskFilter = (tasks: GTDTask[]) => tasks.filter(task => ids.has(idKey(task.id)));
    const planBlocks = snapshot.planBlocks.filter(block => ids.has(idKey(block.taskID)));
    const actualBlocks = snapshot.actualBlocks.filter(block => (block.entry.taskID && ids.has(idKey(block.entry.taskID))) || `${block.entry.title} ${block.entry.note}`.toLocaleLowerCase().includes(needle));
    return { ...snapshot, tasks: taskFilter(snapshot.tasks), completedTasks: taskFilter(snapshot.completedTasks), drawerTasks: taskFilter(snapshot.drawerTasks), crossDayProgressTasks: taskFilter(snapshot.crossDayProgressTasks), completeWithinTasks: taskFilter(snapshot.completeWithinTasks), overdueTasks: taskFilter(snapshot.overdueTasks), deadlineTasks: taskFilter(snapshot.deadlineTasks), planBlocks, actualBlocks, actualEntries: actualBlocks.map(block => block.entry), plannedDuration: planBlocks.reduce((total, block) => total + block.plannedDuration, 0), actualDuration: actualBlocks.reduce((total, block) => total + block.actualDuration, 0) };
  }, [snapshot, query, projectNames]);
  const completedIDs = useMemo(() => new Set(filtered.completedTasks.map(task => idKey(task.id))), [filtered.completedTasks]);
  const blocksByTask = useMemo(() => {
    const index = new Map<string, PlanBlock[]>();
    for (const block of filtered.planBlocks) {
      const key = idKey(block.taskID), blocks = index.get(key);
      if (blocks) blocks.push(block); else index.set(key, [block]);
    }
    return index;
  }, [filtered.planBlocks]);
  const complete = (task: GTDTask) => mutate(db => setTaskCompletionForDay(db, workspaceID, task.id, day, !completedOn(task, day)));
  const openPlan = (taskID?: string) => { setDrawer(null); setEditor({ type: 'plan', taskID: taskID || selectedID }); };
  const openActual = () => {
    const now = new Date(); const minute = now.getHours() * 60 + now.getMinutes();
    setEditor({ type: 'actual', selection: { ...makeScheduleSelection(day, Math.max(0, minute - 30), minute, true), lane: 'actual' } });
  };
  const renderRow = (task: GTDTask) => <TodayTaskRow key={task.id} task={task} day={day} completed={completedIDs.has(idKey(task.id))} selected={sameID(selectedID, task.id)} blocks={blocksByTask.get(idKey(task.id)) || []} projectName={projectNames.get(idKey(task.projectID || ''))} onSelect={() => onSelect(task.id)} onComplete={() => complete(task)} onPlan={() => openPlan(task.id)} onBlock={block => setEditor({ type: 'plan-detail', block })}/>;
  const listSections = [{ title: '已安排时段', tasks: filtered.tasks.filter(task => blocksByTask.has(idKey(task.id)) && !completedIDs.has(idKey(task.id))) }, { title: '待安排', tasks: filtered.drawerTasks }, { title: '已完成', tasks: filtered.completedTasks }].filter(section => status === 'all' || (status === 'done' ? section.title === '已完成' : section.title !== '已完成'));
  return <section className="today-pane" aria-label="今日执行面板">
    <div className="today-controls"><div className="today-mode-switch" aria-label="今日视图"><button aria-pressed={mode === 'list'} className={mode === 'list' ? 'selected' : ''} onClick={() => onMode('list')}><Icon name="menu" size={13}/>清单</button><button aria-pressed={mode === 'schedule'} className={mode === 'schedule' ? 'selected' : ''} onClick={() => onMode('schedule')}><Icon name="clock" size={13}/>日程</button></div><span className="today-completion"><Icon name="check" size={13}/>{snapshot.completedCount}/{snapshot.totalCount} 已完成</span><button className="button small" onClick={() => openPlan()}><Icon name="plus" size={13}/>安排已有任务</button></div>
    <div className="today-search-row"><label className="today-search"><Icon name="search" size={15}/><input id="task-search" placeholder="搜索今日任务、项目、标签或笔记" aria-label="搜索今日任务" value={query} onChange={event => onQuery(event.target.value)}/>{query && <button className="icon-button" aria-label="清除搜索" onClick={() => onQuery('')}><Icon name="close" size={13}/></button>}</label><button className="text-button" onClick={openActual}>补录 / 番茄钟</button></div>
    <div className="today-summary"><div className="today-summary-counts">{(Object.keys(drawerLabels) as DrawerFilter[]).map(filter => <button key={filter} className={filter === 'overdue' ? 'overdue' : ''} onClick={() => setDrawer(filter)}><span>{drawerLabels[filter]}</span><strong>{drawerTasks(filtered, filter).length}</strong></button>)}<button className="today-summary-more" aria-label="查看待安排任务" onClick={() => setDrawer('all')}><Icon name="chevron" size={14}/></button></div>{drawerTasks(filtered, 'progress').slice(0, 2).map(task => <button key={task.id} className="today-progress-summary" onClick={() => onSelect(task.id)}><span className="today-progress-dot"/><span>{task.title}</span><small>跨日推进</small><Icon name="chevron" size={12}/></button>)}</div>
    {mode === 'schedule' ? <TodaySchedule database={database} snapshot={filtered} workspaceID={workspaceID} day={day} selectedID={selectedID} mutate={mutate} onSelection={selection => setEditor(selection.lane === 'plan' ? { type: 'plan', selection, taskID: selectedID } : { type: 'actual', selection })} onPlan={block => setEditor({ type: 'plan-detail', block })} onActual={entry => setEditor({ type: 'actual', entry })} onSelect={onSelect}/> : <div className="today-list"><div className="today-list-filter" aria-label="清单完成状态">{(['all', 'open', 'done'] as const).map(value => <button key={value} aria-pressed={status === value} className={status === value ? 'selected' : ''} onClick={() => setStatus(value)}>{value === 'all' ? '全部' : value === 'open' ? '待办' : '已完成'}</button>)}</div>{listSections.map(section => <section key={section.title} className="today-list-section"><h3>{section.title}<span>{section.tasks.length}</span></h3>{section.tasks.map(renderRow)}{!section.tasks.length && <p className="today-empty">{section.title === '已安排时段' ? '选择“安排已有任务”，或在日程轨道中拖动安排' : section.title === '待安排' ? '当前没有待安排的任务' : '完成任务后会显示在这里'}</p>}</section>)}<section className="today-list-section"><h3>实际记录<span>{filtered.actualBlocks.length}</span><small>{durationLabel(filtered.actualDuration)}{filtered.actualEstimated ? '（跨日估算）' : ''}</small></h3>{filtered.actualBlocks.map(block => <button key={block.id} className="today-actual-list-row" onClick={() => setEditor({ type: 'actual', entry: block.entry })}><Icon name="clock" size={14}/><span>{block.entry.title}<small>{rangeLabel(block.start, block.end)} · {block.entry.source === 'manual' ? '手动补录' : block.entry.source === 'pomodoro' ? '番茄钟' : '正计时'}</small></span><strong>{durationLabel(block.actualDuration)}</strong><Icon name="edit" size={13}/></button>)}{!filtered.actualBlocks.length && <p className="today-empty">开始专注或补录实际后，会显示在这里</p>}</section></div>}
    {composer}
    {drawer !== null && <TodayModal title="待安排任务" wide onClose={() => setDrawer(null)}><div className="today-drawer-filters">{(Object.keys(drawerLabels) as DrawerFilter[]).map(filter => <button key={filter} className={filter === drawer ? 'selected' : ''} aria-pressed={filter === drawer} onClick={() => setDrawer(filter)}>{drawerLabels[filter]} <span>{drawerTasks(filtered, filter).length}</span></button>)}</div><p className="muted">这些任务还没有当天的具体时段。安排时段不改变原有计划范围。</p><div className="today-drawer-list">{drawerTasks(filtered, drawer).map(renderRow)}{!drawerTasks(filtered, drawer).length && <p className="today-empty">当前筛选没有待安排的任务</p>}</div></TodayModal>}
    {editor?.type === 'plan' && <PlanEditor database={database} workspaceID={workspaceID} day={day} snapshot={snapshot} selection={editor.selection} preferredTaskID={editor.taskID} mutate={mutate} onSelect={onSelect} onClose={() => setEditor(null)}/>}
    {editor?.type === 'actual' && <ActualEditor database={database} workspaceID={workspaceID} day={day} selection={editor.selection} entry={editor.entry} preferredTaskID={selectedID} mutate={mutate} onSelect={onSelect} onClose={() => setEditor(null)}/>}
    {editor?.type === 'plan-detail' && <PlanDetails block={editor.block} workspaceID={workspaceID} mutate={mutate} onSelect={onSelect} onClose={() => setEditor(null)}/>}
  </section>;
}

function TodayTaskRow({ task, day, completed, selected, blocks, projectName, onSelect, onComplete, onPlan, onBlock }: { task: GTDTask; day: string; completed: boolean; selected: boolean; blocks: PlanBlock[]; projectName?: string; onSelect: () => void; onComplete: () => void; onPlan: () => void; onBlock: (block: PlanBlock) => void }) {
  return <div className={`today-task-row ${selected ? 'selected' : ''} ${completed ? 'completed' : ''}`}><div className="today-task-row-main"><button className={`task-check priority-${task.priority}`} aria-label={`${completed ? '重新打开' : '完成'} ${day}：${task.title}`} aria-pressed={completed} onClick={onComplete}>{completed && <Icon name="check" size={12}/>}</button><button className="today-task-title" onClick={onSelect}><strong>{task.title}</strong><small>{projectName || '无项目'}{task.planRangeIntent === 'complete-within' ? ' · 区间内完成' : ''}{task.recurrence && task.recurrence !== 'none' ? supportsDailyRecurrence(task) ? ' · 每日实例' : ' · 重复规则' : ''}{task.tags.length ? ` · ${task.tags.map(tag => `#${tag}`).join(' ')}` : ''}</small></button>{!completed && <button className="today-plan-task" onClick={onPlan} aria-label={`安排：${task.title}`}><Icon name="plus" size={12}/>安排</button>}</div>{blocks.length > 0 && <div className="today-task-slots">{blocks.map(block => <button key={block.id} onClick={() => onBlock(block)}><Icon name="clock" size={11}/>{block.isPoint ? `${clockLabel(block.start)} · 时间点` : rangeLabel(block.start, block.end)}</button>)}</div>}</div>;
}
